services:
  admin_office_service:
    container_name: admin_office_service
    env_file:
      - env/dev.env
    build:
      context: ./admin_office_service
      dockerfile: Dockerfile
    volumes:
      - ./admin_office_service:/usr/src/app
    command: air
    ports:
      - 8000:8000
    working_dir: /usr/src/app
    depends_on:
      - nats
    restart: unless-stopped
    networks:
      - wh-network

  customer_office_service:
    container_name: customer_office_service
    env_file:
      - env/dev.env
    build:
      context: ./customer_office_service
      dockerfile: Dockerfile
    volumes:
      - ./customer_office_service:/usr/src/app
    command: air
    ports:
      - 8001:8000
    working_dir: /usr/src/app
    depends_on:
      - nats
    restart: unless-stopped
    networks:
      - wh-network

  auth_service:
    container_name: auth_service
    env_file:
      - env/dev.env
    build:
      context: ./auth_service
      dockerfile: Dockerfile
    volumes:
      - ./auth_service:/usr/src/app
    command: air
    ports:
      - 50051:5000
    working_dir: /usr/src/app
    depends_on:
      - nats
    restart: unless-stopped
    networks:
      - wh-network

  user_service:
    container_name: user_service
    env_file:
      - env/dev.env
    build:
      context: ./user_service
      dockerfile: Dockerfile
    volumes:
      - ./user_service:/usr/src/app
    command: air
    ports: 
      - 50052:5000
    working_dir: /usr/src/app
    depends_on:
      - redis
      - nats
      - auth_service
    restart: unless-stopped
    networks:
      - wh-network

  nats:
    container_name: nats
    entrypoint: "/nats-server -c nats-server.conf -DV"
    image: nats
    ports:
      - 4222:4222
      - 6222:6222
      - 8222:8222
    networks:
      - wh-network

  redis:
    container_name: redis
    image: redis:alpine
    ports:
      - 6379:6379
    networks:
      - wh-network
    restart: always
    entrypoint: redis-server --appendonly yes --maxmemory 112mb --maxmemory-policy allkeys-lru
#    volumes:
#      - ./appdata/redis/data:/data

networks:
  wh-network:
    driver: bridge
